### ISSUE TITLE
Zlib Error: unexpected end of file

### ISSUE THREAD

**Issue by vikramaditya234** [nfriedly/node-unblocker#104]
While i am trying to browse wikipedia using this great tool, I often get server crash with error:

> error Error: unexpected end of file
>       at Zlib._handle.onerror (zlib.js:371:17)
> Error sending 500! Error: Can't set headers after they are sent.
>       at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
>       at Domain.<anonymous> (/var/www/nodejs/node_modules/gatling/gatling.js:81:22)
>       at emitOne (events.js:96:13)
>       at Domain.emit (events.js:188:7)
>       at Unzip.emit (events.js:158:14)
>       at Zlib._handle.onerror (zlib.js:374:10)
> Gatling worker thread 4 up and listening

I dont get this error while browsing use desktop chrome browser but on mobile chrome browser. Just keep clicking on links to navigate within wikipedia and you should see this error by 10th click.

### UPDATE
Found the reason, styles requests are being returned by status code 304 (Not Modified). In which case there will be no content and hence decompress is not needed. A simple check data.remoteResponse.statusCode == 304 should fix the problem. This can be a simple approach, I am sure you will be able to come with a better strategy.
I have proposed change as pull request, hope that helps :)

**Comment by nfriedly** [comment]
Fixed in `v2.0.0`
