### ISSUE TITLE
[Question] Files on root of server

### ISSUE THREAD

**Issue by SpaceboyRoss01** [nfriedly/node-unblocker#108]
I'm trying to write my own web browser for OS.js and I'm trying to figure out how to handle files that are on the root of the server. I'm programming in ES6 so if someone can give me a snippet that I can use to convert the URL from one on the root of the server to the web proxy one, that'll be great.

**Comment by nfriedly** [comment]
I'm not sure I understand the question here.. but this might be what you're looking for: https://github.com/nfriedly/node-unblocker/blob/master/lib/unblocker.js#L152-L195

That code attempts to handle "incorrect" requests, such as those targeted at the root of the proxy server. If it can't figure out what to do, it calls `next()`, and then express can try to match it to some other route or else 404.

For static assets on the proxy server, express.static() can serve those - see https://github.com/nfriedly/node-unblocker/blob/master/examples/nodeunblocker.com/app.js#L68

**Comment by nfriedly** [comment]
Closing this for now. Feel free to re-open if appropriate.
