### ISSUE TITLE
Set custom user agent

### ISSUE THREAD

**Issue by SpaceboyRoss01** [nfriedly/node-unblocker#109]
I want to use a custom user agent but that doesn't seem possible.

**Comment by nfriedly** [comment]
That should be do-able with a custom middleware. I'm on my phone right now, but I'll try and remember to come back and post an example when I'm on a computer.

**Comment by SpaceboyRoss01** [comment]
Ok--Sent from Yandex.Mail for mobile04.12.2018, 17:43, "Nathan Friedly" <notifications@github.com>:That should be do-able with a custom middleware. I'm on my phone right now, but I'll try and remember to come back and post an example when I'm on a computer.

**Comment by nfriedly** [comment]
Here you go: 

* middleware to set a custom user-agent: https://github.com/nfriedly/node-unblocker/blob/master/examples/custom-user-agent/user-agent.js
* example server using it: https://github.com/nfriedly/node-unblocker/blob/master/examples/custom-user-agent/server.js
