### ISSUE TITLE
responseMIddleware replace "title" or create script to rename title?

### ISSUE THREAD

**Issue by FeaturedSpace** [nfriedly/node-unblocker#114]
Basically, I'm trying to create a middleware that will rename the title to some random gibberish to get around the simplest checkers that literally check the Title of the webpage for anything suspicious. I couldn't find anymore issues related to this. Does anyone know why this wouldn't work?

```
function injectScript(data) {
    if (data.contentType == 'text/html') {

        // https://nodejs.org/api/stream.html#stream_transform
        var myStream = new Transform({
            decodeStrings: false,
            transform: function(chunk, encoding, next) {
                chunk = chunk.toString().replace('</body>', '<script>document.head.title = "Nothing to see here."; $(\'title\').html("Nothing to see here!");</script></body>');
                this.push(chunk);
                next();
            }
        });

        data.stream = data.stream.pipe(myStream);
    }
}

var unblockerConfig = {
    prefix: '/proxy/',
    responseMiddleware: [
        injectScript,
        googleAnalyticsMiddleware
    ],
    title: 'Nothing to see here'
};
```

**Comment by nfriedly** [comment]
Hi @FeaturedSpace 

I believe the trouble with that method is that the javascript will execute after the page has loaded with the original title. But if the filter is checking the title before that, then the javascript will never execute. Try this instead:

```js
function changeTitle(data) {
    if (data.contentType == 'text/html') {

        // https://nodejs.org/api/stream.html#stream_transform
        var myStream = new Transform({
            decodeStrings: false,
            transform: function(chunk, encoding, next) {
                chunk = chunk.toString().replace(/<title>.*<\/title>/, '<title>Nothing to see here</title>');
                this.push(chunk);
                next();
            }
        });

        data.stream = data.stream.pipe(myStream);
    }
}

var unblockerConfig = {
    prefix: '/proxy/',
    responseMiddleware: [
        changeTitle,
        googleAnalyticsMiddleware
    ],
};
```

That variation will change the title on the unblocker server, before the checker has a chance to see it.

It's not 100% fool proof, there's a couple of edge cases such as `<title lang="en">foo</title>` or if the tag were split across two packets, this would process them one at a time and neither would match the regex. But, it should handle most cases.

**Comment by FeaturedSpace** [comment]
Thanks. You're awesome.
