### ISSUE TITLE
Heroku Setup Need Help

### ISSUE THREAD

**Issue by SinisterJS** [nfriedly/node-unblocker#116]
Greetings. I’m SinisterJS. I was wondering if you could help me learn step by step how to run the Node Unblocker on a Heroku website. If you could send me theses steps via email, or if you could contact me on discord: Sinister#0026. It’d be greatly appreciated.

**Comment by nfriedly** [comment]
Hi,

As I said in the email, you can follow the instructions on https://devcenter.heroku.com/articles/getting-started-with-nodejs except use the contents of the examples/nodeunblocker.com/ folder for your code.
