### ISSUE TITLE
surviv.io websocket connection

### ISSUE THREAD

**Issue by humphreygaming** [nfriedly/node-unblocker#118]
Either because of cookies or because of the way that the HTTP requests on this thing works, teams can not be created when the request "surviv.io/team" is sent. Returns with "ws://{examplehost}/team failed: Error during WebSocket handshake: Unexpected response code: 404".

From what i understand, it deletes the current proxy site (example: http://{examplehost}/proxy/http://surviv.io/} and replaces it with the hosting site URL only (example: http://{examplehost}.com), thus, making it a blank statement, trying to get a /team response only for it not to exist.

If there is any way to solve this, please provide an explanation. Thank you.

[How to Replicate: Go to any node unblocker host and type in "surviv.io". Once loaded (you can also open the console to view the log), click on "Create Team". It will say "Failed to create team" and will return the error code listed above.]

**Comment by nfriedly** [comment]
Aah, yes, websockets are not currently supported. I don't think they even existed when I first made this. 

That'd be a good thing to add, although it won't be easy.

**Comment by FeaturedSpace** [comment]
What a gamer. Playing Surviv on a proxy. You're making your country proud 😛

**Comment by surviv-ioio** [comment]
I always play surviv on a proxy.

**Comment by FeaturedSpace** [comment]
Is it because your school blocks it, or what?

**Comment by roadkillsanta** [comment]
This is an issue with the specific code in the javascript app file for surviv.io. I have looked at it on my own (because I want to play at school too) and it is just a simple 302 redirect for the websocket request (just like the current automatic redirect for the surviv.io api). Also, @nfriedly needs to add websocket support for it to work.

**Comment by real-cereal-boy** [comment]
They block surviv.io at school as well as yohoho.io but Soon enough node unblocker sites are gonna be blocked too
