### ISSUE TITLE
Vikingpress.online is blocked 

### ISSUE THREAD

**Issue by BraydenTW** [nfriedly/node-unblocker#119]
apparently it vikingpress.online is blocked. Can you make another website with the same functionality?

Thanks!

BraydenTW

**Comment by nfriedly** [comment]
No, sorry, I'm not going to set up any more proxies. However, the code is free and you could run it on a computer at home (or wherever).

**Comment by FeaturedSpace** [comment]
Check out glitch.me, you can host your own for free.
