### ISSUE TITLE
Get error 503: Service Unavailable for Baidu Baike articles

### ISSUE THREAD

**Issue by gkovacs** [nfriedly/node-unblocker#12]
Articles from Baidu Baike (the largest Chinese online encyclopedia), for example, http://baike.baidu.com/view/48682.htm can be visited as-is, but if we try going through Node-Unblocker, I get back a error 503, for example as seen at http://nodeunblocker.com/proxy/http://baike.baidu.com/view/48682.htm (same issues occurs on a node-unblocker instance run on my own server from the latest git checkout).

**Comment by nfriedly** [comment]
Hey, sorry it took a while, but I did get this to work with v1.0.1 - I made two changes that help: 
1) only request gzip encoded content, and 
2) assume it's "raw" deflate (although I'm not sure what's different between regular deflate and "raw"...

**Comment by nfriedly** [comment]
(I no longer have a live proxy, but if you set op your own copy, you should be able to confirm it. I also made things a bit easier to set up with v1.0)
