### ISSUE TITLE
Way to block High-Level Maturity Sites?

### ISSUE THREAD

**Issue by QuantumCat-2585** [nfriedly/node-unblocker#124]
I don't want people to view mature content.

**Comment by nfriedly** [comment]
Yes, you can do that. I just added two examples, a [blacklist](https://github.com/nfriedly/node-unblocker/tree/master/examples/blacklist) one and a [whitelist](https://github.com/nfriedly/node-unblocker/tree/master/examples/whitelist) one.

For the blacklist, you give it a list of the domains that you don't want people to visit, and it will block those.

For the whitelist example, you give it a list of the domains you _do_ want people to visit, and it will block everything else.

It should be pretty straightforward to copy the code from one or the other over to the nodeunblocker.com example; let me know if you get stuck.

I think the whitelist is probably going to be the easier option, because there are a *lot* of mature websites and it's basically impossible to block all of them.

**Comment by real-cereal-boy** [comment]
Yup, sounds like whitelisting is a whole lot easier thank you!

**Comment by real-cereal-boy** [comment]
I placed them in the home directory, however Heroku takes a long time to load just to give me Error In Application 
Use Heroku —tail to view logs

**Comment by real-cereal-boy** [comment]
![4441BEA2-A19D-482C-A892-223E8E141CEA](https://user-images.githubusercontent.com/57405158/70750032-6f142800-1ce2-11ea-8e7f-c6509c2db125.jpeg)

**Comment by nfriedly** [comment]
Hum.. are you able to run that command to get the logs? It would help narrow down the problem.

**Comment by real-cereal-boy** [comment]
I don’t have Heroku CLI Available. What do I do?

**Comment by real-cereal-boy** [comment]
I placed / overwrited all the files in the whitelist folder to the root directory

**Comment by emilhem** [comment]
> I don’t have Heroku CLI Available. What do I do?

You have to get the logs or we can't help at all.

Click that "check your logs for details" link for more help.

Just get the Heroku CLI...

**Comment by real-cereal-boy** [comment]
Jeez

**Comment by real-cereal-boy** [comment]
What if shows personal info of my account.

**Comment by emilhem** [comment]
> What if shows personal info of my account.

That is your problem not ours. Just filter out any data that you don't want the public to see.

No logs, no help.

**Comment by real-cereal-boy** [comment]
Look man I came for help not criticism

**Comment by real-cereal-boy** [comment]
Don’t give me your attitude

**Comment by emilhem** [comment]
Finding what's wrong with your setup/coding/config/environment is like finding a needle in an infinitely large pitch black room unless you share the logs.

**Comment by nfriedly** [comment]
> I placed / overwrited all the files in the whitelist folder to the root directory

I think that overwrited part was the issue. Copying over whitelist.js is fine, but you'll need to combine https://github.com/nfriedly/node-unblocker/blob/master/examples/whitelist/server.js and https://github.com/nfriedly/nodeunblocker.com/blob/master/app.js

Specifically, you'll need to add these parts to `app.js`:

https://github.com/nfriedly/node-unblocker/blob/5fe35200534e2f35b7b76adf42444a794b05b2d9/examples/whitelist/server.js#L5

and

https://github.com/nfriedly/node-unblocker/blob/5fe35200534e2f35b7b76adf42444a794b05b2d9/examples/whitelist/server.js#L10-L15

Presumably with your own choice of domains to whitelist.

**Comment by real-cereal-boy** [comment]
Thank you :)

**Comment by nfriedly** [comment]
Also, you'll want to undo anything you overwrote.

**Comment by real-cereal-boy** [comment]
I’ll just delete the fork and do it again

**Comment by real-cereal-boy** [comment]
> Finding what's wrong with your setup/coding/config/environment is like finding a needle in an infinitely large pitch black room unless you share the logs.

A map won’t help in the dark and neither will a mad guy

**Comment by real-cereal-boy** [comment]
Well not sure if it worked or not but I’ll try to install Heroku CLI, the reason I couldn’t is some requirement problems, sorry

**Comment by IceHacks** [comment]
@real-cereal-boy yeah surviv.io is fun but adult sites aren't

**Comment by Helixable** [comment]
> Well not sure if it worked or not but I’ll try to install Heroku CLI, the reason I couldn’t is some requirement problems, sorry

How on earth did you get surviv.io to work?

**Comment by yodaluca23** [comment]
@nfriedly I am trying to set up the blacklist, I put the files from the example into the root directory, except for the ones that already had a file named that, for those, I merged it... But, what is the format for the code to have blocked? In the server.js? Would it be like this?

```
const unblocker = Unblocker({
  requestMiddleware: [
    blacklist({
      blockedDomains: ["examplesite1.com, examplesite2.com, examplesite3.com"],
      message: "The requested url is not permitted.",
    }),
  ],
});
```
Or,
```
const unblocker = Unblocker({
  requestMiddleware: [
    blacklist({
      blockedDomains: ["examplesite1.com"], ["examplesite2.com"], ["examplesite3.com"],
      message: "The requested url is not permitted.",
    }),
  ],
});
```
Or is it neither? Please help me, thanks!

**Comment by nfriedly** [comment]
None of that looks quite right. For the blocklist, I think this is the format you want:


```js
const unblocker = Unblocker({
  requestMiddleware: [
    blacklist({
      blockedDomains: ["examplesite1.com", "examplesite2.com", "examplesite3.com"],
      message: "The requested url is not permitted.",
    }),
  ],
});
```

Each domain name should be in quotes (`"`), but there should be only one set of brackets (`[` and `]`).

The logs are reporting two different syntax errors, one in a package.json file, one somewhere else.

**Comment by yodaluca23** [comment]
> The logs are reporting two different syntax errors, one in a package.json file, one somewhere else.

Ok, I think I'm doing something wrong, so I added [package-lock.json](https://github.com/yodaluca23/Unblocker_2.0/blob/master/package-lock.json), [server.js](https://github.com/yodaluca23/Unblocker_2.0/blob/master/server.js), and [blacklist.js](https://github.com/yodaluca23/Unblocker_2.0/blob/master/blacklist.js) to the root directory with no edits, except adding the websites we want in server.json... But then  I am confused, how am I supposed to merge the package.js's?

**Comment by nfriedly** [comment]
Looking at https://github.com/yodaluca23/Unblocker_2.0/, you already had a fine package.json - no need to merge in anything. And package-lock.json isn't really necessary as it can generate one automatically.

You also don't need to copy over the entire server.js, instead you need to copy 

https://github.com/nfriedly/node-unblocker/blob/4b05977150f163aaef8607d519501b57bfba575b/examples/blacklist/server.js#L6

and 

https://github.com/nfriedly/node-unblocker/blob/4b05977150f163aaef8607d519501b57bfba575b/examples/blacklist/server.js#L10-L17

into the existing app.js.

**Comment by yodaluca23** [comment]
> Looking at https://github.com/yodaluca23/Unblocker_2.0/, you already had a fine package.json - no need to merge in anything. And package-lock.json isn't really necessary as it can generate one automatically.
> 
> You also don't need to copy over the entire server.js, instead you need to copy
> 
> https://github.com/nfriedly/node-unblocker/blob/4b05977150f163aaef8607d519501b57bfba575b/examples/blacklist/server.js#L6
> 
> and
> 
> https://github.com/nfriedly/node-unblocker/blob/4b05977150f163aaef8607d519501b57bfba575b/examples/blacklist/server.js#L10-L17
> 
> into the existing app.js.

I  did as you describe, but I got this deployment error  (I'm sorry for using your time...):
```
2023-02-06 13:54:17.025: /var/task/app.js:68
var unblocker = new Unblocker({
    ^

SyntaxError: Identifier 'unblocker' has already been declared
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/task/node_modules/gatling/gatling.js:95:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
2023-02-06 13:54:17.142: /var/task/app.js:68
var unblocker = new Unblocker({
    ^

SyntaxError: Identifier 'unblocker' has already been declared
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/task/node_modules/gatling/gatling.js:95:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
/var/task/node_modules/gatling/gatling.js:29
    throw new Error("Too many instant deaths");
    ^

Error: Too many instant deaths
    at createWorker (/var/task/node_modules/gatling/gatling.js:29:11)
    at EventEmitter.<anonymous> (/var/task/node_modules/gatling/gatling.js:53:5)
    at EventEmitter.emit (node:events:527:28)
    at ChildProcess.<anonymous> (node:internal/cluster/primary:203:13)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)


ERROR: Failed to run "npm run start". Start script defined in package.json:

            "scripts": {
                "start":  "gatling app.js"
                 ...
            
Exited with code: 1
2023-02-06 13:54:17.326: /var/task/app.js:68
var unblocker = new Unblocker({
    ^

SyntaxError: Identifier 'unblocker' has already been declared
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/task/node_modules/gatling/gatling.js:95:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

**Comment by nfriedly** [comment]
Oh, sorry, I said copy, but I should have said merge. Specifically, you need to merge

https://github.com/yodaluca23/Unblocker_2.0/blob/fdcd1f22b913dbfdad96a5e9c7ba81a506cec7e9/app.js#L59-L66

and 

https://github.com/yodaluca23/Unblocker_2.0/blob/fdcd1f22b913dbfdad96a5e9c7ba81a506cec7e9/app.js#L68-L76

into something like this:

```js
 const unblocker = Unblocker({ 
    prefix: '/proxy/',
    requestMiddleware: [
        youtube.processRequest,
        blacklist({ 
           blockedDomains: ["example.com", "example2.com", "example3.com"], 
           message: "The requested url is not permitted.", 
        }), 
    ],
    responseMiddleware: [
        googleAnalyticsMiddleware
    ]
});
```

**Comment by yodaluca23** [comment]
> Oh, sorry, I said copy, but I should have said merge. Specifically, you need to merge
> 
> https://github.com/yodaluca23/Unblocker_2.0/blob/fdcd1f22b913dbfdad96a5e9c7ba81a506cec7e9/app.js#L59-L66
> 
> and
> 
> https://github.com/yodaluca23/Unblocker_2.0/blob/fdcd1f22b913dbfdad96a5e9c7ba81a506cec7e9/app.js#L68-L76
> 
> into something like this:
> 
> ```js
>  const unblocker = Unblocker({ 
>     prefix: '/proxy/',
>     requestMiddleware: [
>         youtube.processRequest,
>         blacklist({ 
>            blockedDomains: ["example.com", "example2.com", "example3.com"], 
>            message: "The requested url is not permitted.", 
>         }), 
>     ],
>     responseMiddleware: [
>         googleAnalyticsMiddleware
>     ]
> });
> ```

That works! Thank you so much!
