### ISSUE TITLE
Password Protection

### ISSUE THREAD

**Issue by githubUser673** [nfriedly/node-unblocker#129]
Alright, I got myself into an issue. I've used this for a while but I want to ensure others do not use my instance of Node Unblocker. I've set up a cookie based password system that creates a cookie and then checks it's value. I've made it so that you get redirected back to the original page whenever you try and get to anything else before entering the password. Problem is, `app.get('/proxy*', function(req, res) {
    if(req.cookies.visits==0){
      res.redirect("/password");
    }
});` (The cookie checking method)
does not work with anything after /proxy/ (i.e. /proxy/http://example.com). I want to be able to password-protect my instance because nobody else really knows about this except me. How could I do this?

**Comment by nfriedly** [comment]
Oh, hey, I apologize, I thought I had already responded to this. It sounds like you might have figured something out, but I think the main thing you would need to change is `app.get` to `app.use`. Alternatively, try out basic auth and/or a library.

**Comment by githubUser673** [comment]
I solved this quite a while ago with a cookie based system because I'm not concerned about security, it's just an Unblocker app, with no personal information about any users. I just wanted a password system so a group of people could use it without it blowing up and getting blocked (like other sites). This is aimed at the people in my own school, who I doubt any of them know how to code, nonetheless crack my server's password.
