### ISSUE TITLE
Too Many Redirects

### ISSUE THREAD

**Issue by RoylatGnail** [nfriedly/node-unblocker#130]
When using require('unblocker'); ,it leads to too many redirects. How can I fix this?

**Comment by nfriedly** [comment]
I'm not sure; It could be the configuration, a bad interaction between unblocker and something else you're using, a remote website that doesn't want to be proxied, or any number of other things. 

You might try running some of the [examples](https://github.com/nfriedly/node-unblocker/tree/master/examples) to see if they have different behavior, and if so, try to narrow down the differences between them and your app.

**Comment by RoylatGnail** [comment]
I am currently running a example, here is the link to the source code: https://repl.it/@TaylorLiang/nodeJS

**Comment by RoylatGnail** [comment]
This is also the case with all the other example too.

**Comment by nfriedly** [comment]
Well, that's embarrassing. I can reproduce the issue on repl.co, not sure what's going on. It seems to work locally FWIW.

I think that setting the `host` option might be able to fix that normally, but it wouldn't work in this case because the host seems to be randomly generated after the code is saved..

**Comment by RoylatGnail** [comment]
Do you know how I can fix it?

**Comment by nfriedly** [comment]
Ok, I started playing with it, and I think it's a bug in repl.co's router. They collapse `//` into just `/` when they route requests to the proxy. The proxy sees that, recognizes that the url is incorrect, and attempts to redirect to the correct url. 

A proper fix will have to be implimented by the repl.co folks, although unblocker might be able to detect and work around the bug somewhere in or before this section: 

https://github.com/nfriedly/node-unblocker/blob/master/lib/unblocker.js#L128-L132

**Comment by RoylatGnail** [comment]
ah, thanks

**Comment by nfriedly** [comment]
Bug reported to repl.it here: https://repl.it/bugs/p/router-changes-to-in-url-path

**Comment by nfriedly** [comment]
I published `v2.0.5` with a workaround for this

**Comment by RoylatGnail** [comment]
ah, thank!
