### ISSUE TITLE
Websockets Support

### ISSUE THREAD

**Issue by Helixable** [nfriedly/node-unblocker#136]
I saw previous issues that were caused due to the fact that this unblocker does not support WebSockets. Any progress so far on this issue?

**Comment by Helixable** [comment]
Take a look at this: https://github.com/hipache/hipache

Any idea if that will help?

**Comment by nfriedly** [comment]
Yea, I have a decent idea of what needs to be done, it's just going to be a fair amount of work to do it. For one thing, it will likely need a client-side JS injection in order to ensure the connection goes through the proxy.

**Comment by Helixable** [comment]
That's good news :)
Can't you append a script tag to the HTML being sent to the client?

**Comment by nfriedly** [comment]
Yea, and the basic script is fairly simple - the hard part is testing it and keeping it from breaking (or being broken by) random websites.

**Comment by Helixable** [comment]
Maybe you could make a branch called experimental and push untested ideas and code to it?

**Comment by nfriedly** [comment]
Alright, here you go. It's pretty rough, but I was able to play one round on http://surviv.io/ through it - https://github.com/nfriedly/node-unblocker/tree/websockets

Why don't you try it out and see if a) you can get it to work and b) you can come up with any improvements. (Even just deduplicating things and/or moving some of the new code to the (currently unused) lib/websocket.js file would be helpful.)

**Comment by Helixable** [comment]
No way. You actually did it! That's awesome man! Now for testing and bug fixing.

**Comment by Helixable** [comment]
`TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument 
must be of type function. Received undefined
    at checkListener (events.js:108:11)
    at _addListener (events.js:343:3)
    at Server.addListener (events.js:401:10)
    at /home/runner/Prixy/index.js:46:8
    at Script.runInContext (vm.js:131:20)
    at Object.<anonymous> (/run_dir/interp.js:156:20)
    at Module._compile (internal/modules/cjs/loader.js:115
6:30)
    at Object.Module._extensions..js (internal/modules/cjs
/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32
)
    at Function.Module._load (internal/modules/cjs/loader.
`

That's the error I get when appending ` server.on("upgrade", unblocker.onUpgrade)` right before `server.listen`. Since this branch is separate, do I have to install it manually? Or can a require statement work?

**Comment by Helixable** [comment]
> `TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined at checkListener (events.js:108:11) at _addListener (events.js:343:3) at Server.addListener (events.js:401:10) at /home/runner/Prixy/index.js:46:8 at Script.runInContext (vm.js:131:20) at Object.<anonymous> (/run_dir/interp.js:156:20) at Module._compile (internal/modules/cjs/loader.js:115 6:30) at Object.Module._extensions..js (internal/modules/cjs /loader.js:1176:10) at Module.load (internal/modules/cjs/loader.js:1000:32 ) at Function.Module._load (internal/modules/cjs/loader. `
> 
> That's the error I get when appending ` server.on("upgrade", unblocker.onUpgrade)` right before `server.listen`. Since this branch is separate, do I have to install it manually? Or can a require statement work?

I got the error to disappear by changing `server.on("upgrade", unblocker.onUpgrade)` to `server.on("upgrade", function(){unblocker.onUpgrade});`.

Surviv.io just returns the error `Failed finding game.`

Keep in mind, I have not changed anything at all except that line in my code. I'll try downloading the source files for the WebSockets branch and try with that.

**Comment by nfriedly** [comment]
Yes, this code isn't published to npm yet, so you'll have to install from github instead. Try this:

`npm install --save nfriedly/node-unblocker#websockets`

**Comment by nfriedly** [comment]
I used this example: https://github.com/nfriedly/node-unblocker/blob/websockets/examples/websockets/server.js but, with a trick, I used npm link to make it use my local copy of unblocker instead of one from npm. The above install command should make it use the github branch. I'll try it out on the nodeunblocker.com codebase.

**Comment by Helixable** [comment]
It still doesn't seem to be working. 
This gets logged to the console though:
`Error: getaddrinfo ENOTFOUND img
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
(node:546) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by nfriedly** [comment]
I was getting those two things logged even when it worked.

Here, I made an [websockets](https://github.com/nfriedly/nodeunblocker.com/tree/websockets) branch of the nodeunblocker.com code. All the changes were in this commit: 

https://github.com/nfriedly/nodeunblocker.com/commit/7d7cfea9dbc53bb565cf9174c99a6f9f56c82d07

The cluster bits are not strictly required, but they should offset the performance drop from removing gatling. (Gatling isn't compatible with websockets and I didn't want to take the time to upgrade it.)

I gotta get to work now, so you're on your own for a while. Good luck!

**Comment by Helixable** [comment]
I just got it to work. This is amazing man!
