### ISSUE TITLE
Not an issue, just a question.

### ISSUE THREAD

**Issue by chargedpika** [nfriedly/node-unblocker#139]
Can these still be deployed to heroku without it erroring? Or has that been removed entirely? 
I’m asking because I was getting an error whenever I tried to deploy it. I’m still not really experienced with this kinda stuff, but I’m learning.

**Comment by nfriedly** [comment]
I don't know.. heroku blocked me. It should work, but I can't test it right now.

**Comment by chargedpika** [comment]
Ok.
