### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by RoylatGnail** [nfriedly/node-unblocker#140]
How does this proxy server work? Ive looked through the code, yet still cannot figure it out

**Comment by nfriedly** [comment]
Hey, apologies for the delayed response.

To give you a quick overview, the main files to look at are [unblocker.js](https://github.com/nfriedly/node-unblocker/blob/master/lib/unblocker.js) and [proxy.js](https://github.com/nfriedly/node-unblocker/blob/master/lib/proxy.js). In particular, this these two sections.

This makes the request to the website that is being proxied:
https://github.com/nfriedly/node-unblocker/blob/dded4d34b0d5b99b0f1aa61da78ff95b7b55d2ba/lib/proxy.js#L47

(`proto` there is either `http` or `https` module that is built into node.js)

And then this sends the response headers and body back to the end-user:
https://github.com/nfriedly/node-unblocker/blob/dded4d34b0d5b99b0f1aa61da78ff95b7b55d2ba/lib/proxy.js#L82-L83

The rest of it is basically just tweaking the data to make the urls and headers and such work with the proxy.
