### ISSUE TITLE
Can this thing unblock websites on a school computer?

### ISSUE THREAD

**Issue by martyhil123** [nfriedly/node-unblocker#147]
I myself am using a school computer, however. When I tried to deploy to Heroku and view it was blocked. Are there any websites that can unblock like the titanium network thing? I use a school chromebook. Youtube searches and whatnot get me nowhere. Everything ends up getting patched or blocked.

**Comment by nfriedly** [comment]
Sorry, that sucks. I used to try and keep copies of this online different places, but they all got shut down. 

If you have a computer at home, it's probably possible to set it up for access from elsewhere, but actually getting that working is going to be fairly involved, more than I'd be able to explain, and there's no guarantee it wouldn't also get blocked within a day or two :(

I'm sure there's other options, but I don't know what they are.

**Comment by martyhil123** [comment]
Well do you know how to unblock websites on a school chromebook without having to use a website?

**Comment by nfriedly** [comment]
Nope, sorry

**Comment by martyhil123** [comment]
It's okay.

**Comment by martyhil123** [comment]
it's okay.

**Comment by easella** [comment]
yeah you can change network proxies, but that does not work for me.

**Comment by easella** [comment]
or you can install a vpn through chrome webstore.

**Comment by easella** [comment]
you can also change network proxies.

**Comment by easella** [comment]
or you can use incognito mode if your filtering system is a chrome extension.

**Comment by easella** [comment]
or you can use guest browsing.Keep in mind that the school can still see what you are doing.

**Comment by easella** [comment]
or install something from google play.

**Comment by easella** [comment]
or you can use iframes.

**Comment by nfriedly** [comment]
@myusernamesimo see https://github.com/nfriedly/nodeunblocker.com#running-the-website-on-your-computer for the basic steps.
