### ISSUE TITLE
Does the below code uses your latest library ?

### ISSUE THREAD

**Issue by telegrambotdev** [nfriedly/node-unblocker#148]
It seems like the below website code didnt updated any nearby..(last updated june 2019).
so my question is that code uses this library  ? i mean this updating library ? Anyway your code is great,working amazing fast  :) keep updating bro 

https://github.com/nfriedly/nodeunblocker.com

**Comment by nfriedly** [comment]
Yes, because of this line:

https://github.com/nfriedly/nodeunblocker.com/blob/3ef9c4d8472de2ecb2c4f0744a4b6afb9f7c0e7c/package.json#L13

That `*` means it will use the latest published version when you install it.

**Comment by telegrambotdev** [comment]
> Yes, because of this line:
> 
> https://github.com/nfriedly/nodeunblocker.com/blob/3ef9c4d8472de2ecb2c4f0744a4b6afb9f7c0e7c/package.json#L13
> 
> That `*` means it will use the latest published version when you install it.

Thank you ☺️😊 its very helpful repo :) keep updating..
