### ISSUE TITLE
code

### ISSUE THREAD

**Issue by anominuschan** [nfriedly/node-unblocker#159]
Can i have the startup code for the unblocker im trying to turn it on in repl, https://repl.it/join/taqyetuv-alexiscortes

**Comment by nfriedly** [comment]
So, I split node-unblocker into a library (that I just call "unblocker" now) and a website that uses the library (formerly hosted at nodeunblocker.com)

The code for the library is here in this reop, the code for the website is at https://github.com/nfriedly/nodeunblocker.com

You might also want to see one of the examples, for something that might be easier to get started with: https://github.com/nfriedly/node-unblocker/blob/master/examples/simple/

With either the nodeunblocker.com codebase or one of the examples, the command to set it up is  `npm install` and then the command to start the server is `npm start`. You can inspect the package.json file to see what `npm start` does under the hood.

(I tried your link but it just asks me to log in.)
