### ISSUE TITLE
Round-Robin Hosting?

### ISSUE THREAD

**Issue by zekesonxx** [nfriedly/node-unblocker#16]
I was wondering if you would change it to be more like [Tor2Web](https://tor2web.org), where contributers could run their own node then have it work in a round-robin to handle traffic from the actual domain.

Due to the Heroku domain-binding issue, you could give each node it's own subdomain (like node4.nodeunblocker.com) then have any requests to nodeunblocker.com redirect to a valid node.

Just a thought.

**Comment by nfriedly** [comment]
BTW, with the 1.0 release today, I made some major changes to how cookies are handled, so this might be more feasible. (However, I no longer Hades a live proxy running, so you're on your own for hosting it :/
