### ISSUE TITLE
(this is a question, not an issue)Is this anonymous?

### ISSUE THREAD

**Issue by easella** [nfriedly/node-unblocker#164]
Is this anonymous?If you use this can your school still see what you are doing?

**Comment by nfriedly** [comment]
Your school can see everything you do on their computers and most of what you do on their WiFi if you connect your own phone or computer.

If you set up https for your proxy instance, that will make it harder for the school (or anyone else) to see what you're doing, but still not impossible.

**Comment by easella** [comment]
can you make this an anonymous proxy? Please? I do not want the school knowing that I am using a proxy. I beg you.

**Comment by nfriedly** [comment]
Sorry, it's not really possible.

**Comment by easella** [comment]
they cannot see everything
if you use iframes they cannot see what you are doing

**Comment by nfriedly** [comment]
> if you use iframes they cannot see what you are doing

I find that very unlikely

**Comment by easella** [comment]
I have proof.
The school blocked womginx.synricha.org within a week or so and I did not use it through iframes and the proxies that I have been using for months I use through iframes and they have not been blocked yet.

**Comment by easella** [comment]
actually you are right the school can see everything you do on their computers.
