### ISSUE TITLE
most io games do not work

### ISSUE THREAD

**Issue by easella** [nfriedly/node-unblocker#165]
slither.io,wings.io,wormax.io,frogar io, kize io,mope io, creatur io, buildroyale io, tilefall io, wormate io, piratez io, krew io, lordz io, slither io 2, lordz io 2, moo moo io, spaceblast io, ,diep.io,wiziz.io,zombs.io,zombsroyale,battledudesio,bruhio,skribbl io, krunkerio,evio,warbotio,and repuls io not work.

Also, recaptcha does not work.

**Comment by nfriedly** [comment]
Wow, that's a heck of a list. I'll poke at some of them when I have a minute. 

I have a v3 branch in progress that fixes some things, but I'm not done with it yet.

**Comment by easella** [comment]
when are you going to be done with it?

**Comment by nfriedly** [comment]
🤷‍♂️
