### ISSUE TITLE
how can i get links

### ISSUE THREAD

**Issue by Susdevlmao** [nfriedly/node-unblocker#175]
I wann get links to this unblocker how ca i get links

**Comment by easella** [comment]
heres one
[click here](https://luckypapers.awdrgyjil1234.repl.co)

**Comment by easella** [comment]
heres another one:
[click here](https://noderlol.awdrgyjil1234.repl.co/)

**Comment by Susdevlmao** [comment]
> heres one
> [click here](https://luckypapers.awdrgyjil1234.repl.co)

this is a ela paper

**Comment by easella** [comment]
huh?

**Comment by Susdevlmao** [comment]
anyway easella do u know a proxy that unblocks tubi?? link : tubi.tv

**Comment by easella** [comment]
maybe

**Comment by easella** [comment]
by the way try my unblocked games site:
[click here](https://mathpractice.awdrgyjil1234.repl.co/)

**Comment by easella** [comment]
it has tubi tv

**Comment by Susdevlmao** [comment]
u know another one?

**Comment by Susdevlmao** [comment]
cuz its blocked for me :(

**Comment by easella** [comment]
whats blocked 4 u

**Comment by easella** [comment]
u mean herokuapp is blocked for you?

**Comment by easella** [comment]
or is it my games site?

**Comment by Susdevlmao** [comment]
ur website is working but twitter login doesnt work and also tubi doesnt work

**Comment by easella** [comment]
here are some holyunblocker links:
https://cycle.ga
https://challengehill.co
https://grammarfiles.net
https://precede,design
https://beachball.xyz
https://energystorm.xyz/
https://referencefile.org
https://catcoup.xyz/
https://x-ray-edu.gq/
https://thermomap.xyz/
http://depthvoid.gq/
https://degreelookup.org
http://degreefinder.cf/
http://holyubofficial.ml/

**Comment by easella** [comment]
tubi doesnt work?

**Comment by easella** [comment]
twitter login does work

**Comment by Susdevlmao** [comment]
yea

**Comment by easella** [comment]
why did u say it doesnt work when it does

**Comment by easella** [comment]
so tubi doesnt work?

**Comment by Susdevlmao** [comment]
yea it doesnt

**Comment by easella** [comment]
rats

**Comment by easella** [comment]
do u like my games site?

**Comment by Susdevlmao** [comment]
because it was blocked but  when i put it again reload it worked

**Comment by easella** [comment]
oh

**Comment by Susdevlmao** [comment]
yea its good btw my brother is Machi9

**Comment by easella** [comment]
oh

**Comment by easella** [comment]
he uses my game site!

**Comment by easella** [comment]
does netflix work

**Comment by Susdevlmao** [comment]
yea :)

**Comment by easella** [comment]
really?

**Comment by Susdevlmao** [comment]
i just wanna unblock either tubi crunchyroll funimation or twitter Yea

**Comment by easella** [comment]
netflix actually works? gimme a screenshot?

**Comment by Susdevlmao** [comment]
wait i didnt try netflix

**Comment by easella** [comment]
try it

**Comment by easella** [comment]
tell me if it works

**Comment by Susdevlmao** [comment]
and he doesnt need netflix its alr unblocked see sometimes out school plays movies for us using netlifx
lemme try it

**Comment by easella** [comment]
oh

**Comment by easella** [comment]
well try the netflix i put on my site

**Comment by easella** [comment]
tell me if it works and gimme a screenshot

**Comment by Susdevlmao** [comment]
sorry if its rude but it works but i dont wanna risk trying out the login

**Comment by easella** [comment]
please

**Comment by easella** [comment]
the proxy is a trusted proxy

**Comment by Susdevlmao** [comment]
no im sorry

**Comment by easella** [comment]
please i wanna know if it works

**Comment by Susdevlmao** [comment]
its my parents acc no even mine

**Comment by easella** [comment]
do u want me 2 add any more games,social media sites, or video streaming sites

**Comment by Susdevlmao** [comment]
tubi
or pluto

**Comment by Susdevlmao** [comment]
and login support for twitter

**Comment by easella** [comment]
ok lemme try pluto and twitter works for logging in

**Comment by Susdevlmao** [comment]
ok

**Comment by MrMachi9** [comment]
hey bro

**Comment by MrMachi9** [comment]
how yall doin

**Comment by easella** [comment]
hi

**Comment by easella** [comment]
im trying pluto

**Comment by easella** [comment]
hold on a minute

**Comment by Susdevlmao** [comment]
ok

**Comment by easella** [comment]
i added it

**Comment by easella** [comment]
tell me if it works

**Comment by MrMachi9** [comment]
you know that link you gave me still hasnt been blocked

**Comment by easella** [comment]
does it work

**Comment by Susdevlmao** [comment]
ok

**Comment by easella** [comment]
oh ok

**Comment by MrMachi9** [comment]
yea

**Comment by MrMachi9** [comment]
its perfect

**Comment by easella** [comment]
really it works

**Comment by easella** [comment]
pluto tv works

**Comment by Susdevlmao** [comment]
send me ur unblocked site again

**Comment by easella** [comment]
ok

**Comment by Susdevlmao** [comment]
i think they blocked it or something

**Comment by easella** [comment]
https://mathpractice.awdrgyjil1234.repl.co/

**Comment by MrMachi9** [comment]
that one is blocked

**Comment by easella** [comment]
http://ioh1h.sse.codesandbox.io/

**Comment by MrMachi9** [comment]
that one works

**Comment by Susdevlmao** [comment]
yea it is

**Comment by easella** [comment]
ok

**Comment by easella** [comment]
tell me if its blocked

**Comment by easella** [comment]
ill send u a new one

**Comment by Susdevlmao** [comment]
ok

**Comment by easella** [comment]
im gonna send u more links

**Comment by Susdevlmao** [comment]
ok

**Comment by easella** [comment]
https://schoolstudies.awdrgyjil1234.repl.co/

**Comment by easella** [comment]
https://schooltips.herokuapp.com/

**Comment by MrMachi9** [comment]
https://schoolstudies.awdrgyjil1234.repl.co/ is blocked https://schooltips.herokuapp.com/ is allowed

**Comment by easella** [comment]
oh ok

**Comment by Susdevlmao** [comment]
ok school studdies is working for me

**Comment by easella** [comment]
do u want me 2 add any more games

**Comment by Susdevlmao** [comment]
pluto doesnt work btw

**Comment by MrMachi9** [comment]
krunker dosent work on it

**Comment by easella** [comment]
ur brother said it does

**Comment by Susdevlmao** [comment]
no pluto doesnt work

**Comment by Susdevlmao** [comment]
the link works the school studies does

**Comment by easella** [comment]
ill put a new one on

**Comment by Susdevlmao** [comment]
not pluto tv

**Comment by MrMachi9** [comment]
it didnt work for me
 and how do you know hes my broyher

**Comment by MrMachi9** [comment]
brother

**Comment by Susdevlmao** [comment]
![Screenshot 2021-05-19 1 46 20 PM](https://user-images.githubusercontent.com/82054063/118859896-becc2b00-b8a8-11eb-886c-227fb2b9646b.png)

**Comment by easella** [comment]
he told me

**Comment by MrMachi9** [comment]
oh

**Comment by easella** [comment]
whats not working

**Comment by MrMachi9** [comment]
but krunker didnt work for me

**Comment by Susdevlmao** [comment]
and also im trying to see if twitter login works

**Comment by Susdevlmao** [comment]
and pluto doesnt work too

**Comment by easella** [comment]
ok

**Comment by easella** [comment]
tell me if it works

**Comment by easella** [comment]
whats wrong with pluto?

**Comment by MrMachi9** [comment]
i want you to try this game outhttps://rawcdn.githack.com/scheng123321/1v1-lol/dd12bf65e0f07e564bcae1c343fcccdb6a383fce/index.html#

**Comment by Susdevlmao** [comment]
when i wana watch pluto it just loads

**Comment by Susdevlmao** [comment]
ss here : 
![Screenshot 2021-05-19 1 46 20 PM](https://user-images.githubusercontent.com/82054063/118860199-1a96b400-b8a9-11eb-9b37-d4a116d9806b.png)

**Comment by Susdevlmao** [comment]
just tried twitter it doesnt work as well

**Comment by easella** [comment]
so the videos dont load

**Comment by easella** [comment]
twitter works i tried it

**Comment by Susdevlmao** [comment]
yea it doesnt load

**Comment by easella** [comment]
gimme a screenshot of twitter

**Comment by Susdevlmao** [comment]
when i login it says ok then goes back to the login page

**Comment by easella** [comment]
no it doesnt, i tried it. it doesnt

**Comment by Susdevlmao** [comment]
twitter works?

**Comment by easella** [comment]
yeah

**Comment by easella** [comment]
it does

**Comment by Susdevlmao** [comment]
pluto now loads then pauses

**Comment by MrMachi9** [comment]
can you show me a sceen shot of you in a krunker match cause krunker dosent work

**Comment by easella** [comment]
i know krunker doesnt work

**Comment by MrMachi9** [comment]
oh

**Comment by easella** [comment]
sorry

**Comment by easella** [comment]
i know u love krunker

**Comment by easella** [comment]
try the krunker proxy site
https://browserfps.com

**Comment by easella** [comment]
![image](https://user-images.githubusercontent.com/74786054/118860924-ed96d100-b8a9-11eb-8ba8-a8e3f8b09956.png)

**Comment by easella** [comment]
try the krunker proxy site
https://browserfps.com

**Comment by Susdevlmao** [comment]
the twitter is blocked when i succesfuly log in

**Comment by MrMachi9** [comment]
that krunker link is blocked

**Comment by Susdevlmao** [comment]
pluto doesnt work btw

**Comment by easella** [comment]
darn

**Comment by MrMachi9** [comment]
and i tryed it on holy unblocker and it donsnt work

**Comment by easella** [comment]
i know

**Comment by MrMachi9** [comment]
that one is blocked too

**Comment by easella** [comment]
darn

**Comment by easella** [comment]
do u want me 2 add any more games?

**Comment by MrMachi9** [comment]
no just fix krunker

**Comment by Susdevlmao** [comment]
also fix pluto

**Comment by Susdevlmao** [comment]
ok what about instagram

**Comment by easella** [comment]
reddit works

**Comment by Susdevlmao** [comment]
it directs me to unsafe

**Comment by easella** [comment]
type thisisunsafe

**Comment by Susdevlmao** [comment]
send new link please?

**Comment by Susdevlmao** [comment]
no i need a new link

**Comment by easella** [comment]
what do u mean

**Comment by easella** [comment]
simply type thisisunsafe

**Comment by MrMachi9** [comment]
it works for me

**Comment by MrMachi9** [comment]
it should work for you

**Comment by easella** [comment]
yeah

**Comment by easella** [comment]
ur brother is lying

**Comment by MrMachi9** [comment]
no its just that were in different grades so things don work

**Comment by MrMachi9** [comment]
but it does work for me

**Comment by easella** [comment]
huh?

**Comment by MrMachi9** [comment]
huh?

**Comment by MrMachi9** [comment]
h






































h

**Comment by easella** [comment]
do u want me to add any more games?

**Comment by MrMachi9** [comment]
war brokers.io

**Comment by easella** [comment]
cant add that.anything else

**Comment by MrMachi9** [comment]
no

**Comment by easella** [comment]
ok

**Comment by Susdevlmao** [comment]
add a site where  i can watch hxh

**Comment by easella** [comment]
whats that

**Comment by Susdevlmao** [comment]
hunter x hunter search it up

**Comment by easella** [comment]
gimme the link 2 the site

**Comment by Susdevlmao** [comment]
pluto.tv or tubi.tv or crunchyroll.com
or funimation.com

**Comment by easella** [comment]
oh

**Comment by MrMachi9** [comment]
can you add 1v1 battle

**Comment by MrMachi9** [comment]
to the site

**Comment by easella** [comment]
i did

**Comment by easella** [comment]
![image](https://user-images.githubusercontent.com/74786054/119171937-4180f180-ba33-11eb-819b-51f9514e7573.png)

**Comment by Susdevlmao** [comment]
did u add the anime watching sites??

**Comment by MrMachi9** [comment]
no i mean this https://1v1battle.com/

**Comment by easella** [comment]
not yet

**Comment by easella** [comment]
i added funimation

**Comment by easella** [comment]
i cant add 1v1 battle 
u have 2 download it

**Comment by Susdevlmao** [comment]
U DID NO WAY THANKS

**Comment by Susdevlmao** [comment]
i need a new link for ur site again

**Comment by MrMachi9** [comment]
what about bullet party

**Comment by easella** [comment]
ok
http://ioh1h.sse.codesandbox.io/

**Comment by easella** [comment]
https://schooltips.herokuapp.com/

**Comment by easella** [comment]
https://29ls8.sse.codesandbox.io/

**Comment by easella** [comment]
i cant add bulletparty

**Comment by easella** [comment]
https://is9t6.sse.codesandbox.io/

**Comment by easella** [comment]
https://buqd7.sse.codesandbox.io/

**Comment by easella** [comment]
https://tovjb.sse.codesandbox.io/

**Comment by MrMachi9** [comment]
what about the real minecraft if not lets tryhttps://play.google.com/store/apps/details?id=com.hgamesart.ironmech&hl=en_US&gl=US

**Comment by ahyowinner** [comment]
i would like an online site where i can make music without having to make a beat i just want to record my word with a beat but i need an ONLINE site and if not any flash game

**Comment by 0x00009b** [comment]
> i would like an online site where i can make music without having to make a beat i just want to record my word with a beat but i need an ONLINE site and if not any flash game


Yk ima just say this here and now I feel sorry for @nfriedly and the lad having his entire project, over ran by kids trying to unblock online games. I just want you all to know GitHub is a place for developers to build, collaborate, manage and share there software and contribute to the open source community, GitHub is not a social media site/message board I would suggest moving to a platform like Discord for things like this. It is also a good idea to use proper spelling and grammar when opening/discussing and issues


Ps: sorry for the rant

**Comment by ahyowinner** [comment]
so i will take that as a you can not do it

**Comment by Susdevlmao** [comment]
> > i would like an online site where i can make music without having to make a beat i just want to record my word with a beat but i need an ONLINE site and if not any flash game
> 
> Yk ima just say this here and now I feel sorry for @nfriedly and the lad having his entire project, over ran by kids trying to unblock online games. I just want you all to know GitHub is a place for developers to build, collaborate, manage and share there software and contribute to the open source community, GitHub is not a social media site/message board I would suggest moving to a platform like Discord for things like this. It is also a good idea to use proper spelling and grammar when opening/discussing and issues
> 
> Ps: sorry for the rant

someones mad lmfao

**Comment by Willbil** [comment]
@easella the youtube/ reddit/ funimation unblocker is down

**Comment by easella** [comment]
i put it back up

**Comment by easella** [comment]
i fixed it

**Comment by Susdevlmao** [comment]
add crunchyroll.com

**Comment by easella** [comment]
lemme see

**Comment by easella** [comment]
i cant.
it has cloudflare checks
![image](https://user-images.githubusercontent.com/74786054/119272245-1208eb00-bbd3-11eb-8a07-f780ca917430.png)

**Comment by ahyowinner** [comment]
can you can unblock a cool flash game and if not can you unblock an online music maker

**Comment by easella** [comment]
ok

**Comment by easella** [comment]
i cant add super crime steel war hero

**Comment by ahyowinner** [comment]
any flash games

**Comment by easella** [comment]
no. only if they work with ruffle or swf2js

**Comment by ahyowinner** [comment]
any minecrft that you can do with friends

**Comment by easella** [comment]
no

**Comment by ahyowinner** [comment]
any muscic makers online to make music

**Comment by easella** [comment]
like what music makers?

**Comment by ahyowinner** [comment]
like an onlie site where you pick a beat and write lyrics to the beat and export it

**Comment by easella** [comment]
gimme the link to the site

**Comment by ahyowinner** [comment]
i do not have one

**Comment by easella** [comment]
then i cant add it

**Comment by ahyowinner** [comment]
https://panzoid.com/

**Comment by ahyowinner** [comment]
can you unblock that

**Comment by easella** [comment]
yeah

**Comment by ahyowinner** [comment]
tell me when you do

**Comment by easella** [comment]
added it

**Comment by ahyowinner** [comment]
where can i get it

**Comment by easella** [comment]
wait 5 seconds

**Comment by easella** [comment]
https://bittersweet-rattle-devourer.glitch.me/panzoid.html

**Comment by 0x00009b** [comment]
> > > i would like an online site where i can make music without having to make a beat i just want to record my word with a beat but i need an ONLINE site and if not any flash game
> > 
> > 
> > Yk ima just say this here and now I feel sorry for @nfriedly and the lad having his entire project, over ran by kids trying to unblock online games. I just want you all to know GitHub is a place for developers to build, collaborate, manage and share there software and contribute to the open source community, GitHub is not a social media site/message board I would suggest moving to a platform like Discord for things like this. It is also a good idea to use proper spelling and grammar when opening/discussing and issues
> > Ps: sorry for the rant
> 
> someones mad lmfao

Not mad would just like to see some real work get done ✔️

**Comment by nfriedly** [comment]
Yea.. I'm going to go ahead and close this ticket and unsubscribe myself. 

I know there's a discord server set up, that might be a better place for this discussion.
