### ISSUE TITLE
 iframe blocks

### ISSUE THREAD

**Issue by easella** [nfriedly/node-unblocker#176]
this is what happens when i use google through iframes with the nodeunblocker
![image](https://user-images.githubusercontent.com/74786054/119414279-422cb880-bcbd-11eb-9c03-37eaa0af4a6f.png)

**Comment by nfriedly** [comment]
That error tells me that it's not even connecting to the server where unblocker is running. It could mean that unblocker crashed, but it could also just be a typo or any of a dozen other issues. There's really not enough information here to know.

You should confirm that the url is correct, and then check to see if there are any logs of what happened on the server.

**Comment by easella** [comment]
no it doesnt.

**Comment by easella** [comment]
and inspect is blocked on my chromebook

**Comment by easella** [comment]
![image](https://user-images.githubusercontent.com/74786054/119560109-87122700-bd71-11eb-9707-8a2d69e5e040.png)

**Comment by easella** [comment]
the url is correct
![image](https://user-images.githubusercontent.com/74786054/119560164-942f1600-bd71-11eb-8e42-6890392325c8.png)

**Comment by easella** [comment]
![image](https://user-images.githubusercontent.com/74786054/119560213-a27d3200-bd71-11eb-8845-2ae89d509f5f.png)

**Comment by nfriedly** [comment]
Cool, I'm going to close this then.
