### ISSUE TITLE
NOTHING WORKS

### ISSUE THREAD

**Issue by josetzunun** [nfriedly/node-unblocker#180]
NOTHING IS WORKING IN THERE I TRIED OPENING YOUTUBE NOTHING WORKS FIX IT.

**Comment by nfriedly** [comment]
You fix it. 

I don't like being yelled at, and I don't like your attitude.

This project is a culmination of years worth of effort that I give away at a goodness of my heart. If it's not working for you, then I'm sorry, but that doesn't entitle you to yell at me or demand more from me.

Please reward your request.

**Comment by easella** [comment]
yeah. respect nfriedly.

**Comment by nfriedly** [comment]
Yea.. I'm just going to close this.
