### ISSUE TITLE
No matching version found for gatling@^2.0.0.

### ISSUE THREAD

**Issue by CrateTech** [nfriedly/node-unblocker#183]
I get this error when trying anything, I try to install the gatling package but it doesn't work. Please help. I know there is probably an easy fix I just cant find it.

**Comment by CrateTech** [comment]
Works now! Thank you so much! I had actually already *sort of* fixed this just by removing the Gatling requirement in package.json, but this works much better.

**Comment by nfriedly** [comment]
Cool. I'm not sure what happened with npm, but yea, the v2.0 of gatling is less invasive so that things more or less work without it, it just improves capacity/uptime. I should probably update the nodeunblocker.com readme...
