### ISSUE TITLE
new node unlocked links 

### ISSUE THREAD

**Issue by 970bih30-boy** [nfriedly/node-unblocker#190]
just want a node unblocker link

**Comment by 970bih30-boy** [comment]
or an alt link to it

**Comment by MadKamel** [comment]
proxy.crove.io iirc, but this is exactly the wrong place to ask.

**Comment by 970bih30-boy** [comment]
huh

**Comment by 970bih30-boy** [comment]
do you know where to ask

**Comment by nfriedly** [comment]
Yeah, @MadKamel is correct, github issues isn't really an appropriate place for this kind of discussion.  https://discord.gg/unblock is one place you could try.

I'm going to go ahead and close this, though.
