### ISSUE TITLE
Next.js support

### ISSUE THREAD

**Issue by mrchilliballs** [nfriedly/node-unblocker#208]
I was trying to get node-unblocker working with Next.js but I don’t think it is possible. It tried using next-connect and normal API routes but nothing seems to work. The only way I’ve been able to use node-unblocker with Next.js is with a custom server, which is not supported for deployment in vercel, and it does work in Heroku but they are removing their free tier next month.
Is there any possibility you could provide full or partial Next.js support?
Thanks in advance and btw this project is really nice, it’s still maintained after so many years.

**Comment by nfriedly** [comment]
Sorry I missed this when  it was first posted, but, yeah, I think Vercel is static content only, at least on their free tier, so that won't work with unblocker.

**Comment by mrchilliballs** [comment]
> Sorry I missed this when it was first posted, but, yeah, I think Vercel is static content only, at least on their free tier, so that won't work with unblocker.
It is not, Vercel can do static and dynamic in the free tier.

**Comment by nfriedly** [comment]
Oh, hum. I don't know how to do it off the top of my head, but I suppose it might be possible after all.
