### ISSUE TITLE
Setting a static URL without typing it after the prefix

### ISSUE THREAD

**Issue by snaildos** [nfriedly/node-unblocker#239]
I want to know how I can set a URL for example https://google.com without writing it after the prefix.

**Comment by snaildos** [comment]
I've tried intercepting via middleware, however that only works when a URL is written after the prefix, not just the prefix. I've also tried getting express to redirect without updating the URL, but that also caused issues with images not loading.
Hope you have some advice.

**Comment by nfriedly** [comment]
Hey, unfortunately the URL structure is really baked in to the current design of unblocker. That's something I started to address in the v3 branch, but I haven't made much progress on that recently. (I've only been able to put significant amounts of work in when I have a consulting job that uses it, and I haven't had any of those recently.)

**Comment by snaildos** [comment]
> Hey, unfortunately the URL structure is really baked in to the current design of unblocker. That's something I started to address in the v3 branch, but I haven't made much progress on that recently. (I've only been able to put significant amounts of work in when I have a consulting job that uses it, and I haven't had any of those recently.)

Hey, thanks for the reply. Appreciated. So there is no way I can set the default URL to be example.com without it showing up in the URL bar? or any other method you may know of?

**Comment by snaildos** [comment]
> It will require fairly involved code changes to unblocker.

I understand, but is there nothing you can recommend to me that I can do? Like using another proxy ontop of node-unblocker or something?

**Comment by nfriedly** [comment]
Well, I'm not sure another proxy in front of unblocker would work, but you could try out another proxy entirely (https://github.com/nfriedly/node-unblocker/wiki/Alternative-Projects lists a few), or you could try and make the changes to unblocker. The work is started in the v3 branch, but it's not really in a functioning state there.

**Comment by snaildos** [comment]
Cheers for the reply mate. Got it all sorted, love your work a ton. Resolved by putting another middle-end in front of it.
