### ISSUE TITLE
https://www.youtube.com/embed/XGxIE1hr0w4 --This type of URL cannot be proxied

### ISSUE THREAD

**Issue by MassSmith** [nfriedly/node-unblocker#257]
node-unblocker is a great project, I love it, I have been using it for more than 6 years.
Recently I tried the youtube proxy function, it is very useful and smooth, but one of the youtube url formats does not seem to work properly, for example:
https://www.youtube.com/embed/XGxIE1hr0w4
and this format is very common, many videos embedded on web pages are in this URL format.
I really hope to add this function, thank the project author for his great contribution.
(My English is very poor, the above is translated by a translator)

**Comment by MassSmith** [comment]
Another small bug was found
https://****.***.***/proxy/https://www.youtube.com/watch?v=XGxIE1hr0w4
In areas where youtube cannot be accessed, the cover image cannot be displayed. Here is the webpage source code:

<!DOCTYPE html>
<head>
<title>Never Gonna Give You Up | Rick Astley Rocks New Year's Eve - BBC</title>
<meta name="ROBOTS" content="NOINDEX, NOFOLLOW"/>
</head>
<body>
<h1>Never Gonna Give You Up | Rick Astley Rocks New Year's Eve - BBC</h1>
<video controls poster="https://i.ytimg.com/vi/XGxIE1hr0w4/maxresdefault.jpg" style="width: 100%">
  <source type="video/mp4" src="/proxy/https://rr4---sn-a5mekn6z.googlevideo.com/videoplayback?expire=1717617479&amp;ei=525gZszTJPPbsfIP4KSzkAg&amp;ip=148.135.58.214&amp;id=o-AI-Xai54nrsuY4O2U6ClbzpxJ9ODG8dmgzO5HC-C4sBv&amp;itag=18&amp;source=youtube&amp;requiressl=yes&amp;xpc=EgVo2aDSNQ%3D%3D&amp;mh=V5&amp;mm=31%2C26&amp;mn=sn-a5mekn6z%2Csn-o097znzk&amp;ms=au%2Conr&amp;mv=m&amp;mvi=4&amp;pl=17&amp;initcwndbps=881250&amp;bui=AbKP-1P85ed2_IJkTc6_URDBHr38gg0pEtkafD9XIgdhdfFp0NL9osayzpPhPUpeHbHePu373lKLNBTM&amp;spc=UWF9fyxk7BOn58LMAtf0H-q3gnRvw1Kx7YGnIRW3qmgq1_139fPGV-pPJIsa&amp;vprv=1&amp;svpuc=1&amp;mime=video%2Fmp4&amp;ns=kgIjSPieDV3pXvnAPgd46bkQ&amp;rqh=1&amp;gir=yes&amp;clen=21113780&amp;ratebypass=yes&amp;dur=233.546&amp;lmt=1704097448079549&amp;mt=1717595571&amp;fvip=2&amp;c=WEB&amp;sefc=1&amp;txp=5538434&amp;n=fxXnocah1cMQbQ&amp;sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&amp;sig=AJfQdSswRQIgFG1FX7oyNeOns5n0uGLLYS5uxYkLQMaYALK2zkpos6oCIQC6XbXXKng1CrNDHYW9DBRCnPDrGuan_QnaiMabct2X7Q%3D%3D&amp;lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&amp;lsig=AHlkHjAwRAIgZccRnR-rSMaWtD7iemu3lxQlMl74fxES7djSX5SNLgcCICpRLAqyrMnRQe2c-Pt5NQO5pVedqJtvYnNiELPo2Kby">
</video>
<p>Rickrolling into 2024 😉 #RickAstleyRocksNewYearsEve #iPlayer #Sounds #NeverGonnaGiveYouUp
<br>
<br>Subscribe and 🔔 to the BBC 👉 https://bit.ly/BBCYouTubeSub
<br>Watch the BBC first on iPlayer 👉 https://bbc.in/iPlayer-Home
<br>
<br>Join celebrated legend, Rick Astley, as he puts on a spectacular New Year’s Eve show. Coming from the iconic Roundhouse in Camden on Tuesday 12th December, the TV event will see Rick joined on stage by some very special guests, with live performances that will bring the house down and ring in the brand-new year. Performing his global hits and some surprise songs, Rick and his guests will bring the party right into 2024.
<br>
<br>All our TV channels and S4C are available to watch live through BBC iPlayer, although some programmes may not be available to stream online due to rights. If you would like to read more on what types of programmes are available to watch live, check the 'Are all programmes that are broadcast available on BBC iPlayer?' FAQ 👉 https://bbc.in/2m8ks6v.</p>
</body>
</html>

**Comment by MassSmith** [comment]
Another small bug was found
https://****.***.***/proxy/https://www.youtube.com/watch?v=XGxIE1hr0w4
In areas where youtube cannot be accessed, the cover image cannot be displayed. Here is the webpage source code:
<img width="679" alt="071416" src="https://github.com/nfriedly/node-unblocker/assets/43735033/2fe2349b-b951-4a77-b052-e7878cc5f0e9">

**Comment by nfriedly** [comment]
Aah, good points. For the first one, you might just need to change this line to include /embed urls:

https://github.com/nfriedly/node-unblocker/blob/1f5bdf3eb46be30501450f81165ef99f2dc9130b/examples/youtube/youtube.js#L8

For the second one, I think you need to add `/proxy/` to the start of the poster url here:

https://github.com/nfriedly/node-unblocker/blob/1f5bdf3eb46be30501450f81165ef99f2dc9130b/examples/youtube/youtube.js

Also, I think we should add `poster=` to this regex, although I don't think it affects the youtube page

https://github.com/nfriedly/node-unblocker/blob/1f5bdf3eb46be30501450f81165ef99f2dc9130b/lib/url-prefixer.js#L24

I don't have time to test these out right now, but that's my best guess as to the fixes; feel free to try them out if you have the time.

**Comment by MassSmith** [comment]
Thank you very much for helping me in your busy schedule. I have done what you told me and the cover image problem has been solved.
But the first problem still exists. The corresponding source code has been changed to: “if (hostname === "www.youtube.com" && (pathname === "/watch" || pathname === "/embed")) {”
But when proxying a URL in the format of https://www.youtube.com/embed/XGxIE1hr0w4, it cannot be played. Here are the test results:
<img width="767" alt="205231" src="https://github.com/nfriedly/node-unblocker/assets/43735033/884245ae-c888-4f63-8d00-98cf4950bab7">

<img width="802" alt="205700" src="https://github.com/nfriedly/node-unblocker/assets/43735033/75835bcd-8a15-4521-aca4-3d6dca0ad6ac">

Thank you again! !

**Comment by MassSmith** [comment]
In addition, there is no error output on the console。
<img width="596" alt="211317" src="https://github.com/nfriedly/node-unblocker/assets/43735033/1442375c-5ac5-4c7a-9b20-34b7a541c968">

**Comment by nfriedly** [comment]
Oh, I see. For `/watch`, the video id is in the querystring, but for `/embed` it's in the path, so my check wouldn't work.

Instead of trying to guess whether or not it's a youtube URL ourselves, we should just ask ytdl. And, come to think of it, we could drop the first part and make this page work for other domains like youtu.be and m.youtube.com:

Can you try this and let me know if it works?

```diff
-  if (hostname === "www.youtube.com" && (pathname === "/watch" || pathname === "/embed")) {
+  if (ytdl.validateURL(data.url)) {
```

**Comment by MassSmith** [comment]
> Oh, I see. For `/watch`, the video id is in the querystring, but for `/embed` it's in the path, so my check wouldn't work.
> 
> Instead of trying to guess whether or not it's a youtube URL ourselves, we should just ask ytdl. And, come to think of it, we could drop the first part and make this page work for other domains like youtu.be and m.youtube.com:
> 
> Can you try this and let me know if it works?
> 
> ```diff
> -  if (hostname === "www.youtube.com" && (pathname === "/watch" || pathname === "/embed")) {
> +  if (ytdl.validateURL(data.url)) {
> ```

Really Great！！！ Works perfectly！！！
This problem is perfectly solved!!
Thank you again!!

**Comment by nfriedly** [comment]
I went ahead and incorporated the changes so that everyone else will get it going forward. Thanks for testing things for me!

**Comment by MassSmith** [comment]
Thank you so much for everything you do!!
^_^
