### ISSUE TITLE
how to add ads in unblocked website 

### ISSUE THREAD

**Issue by bobwatcherx** [nfriedly/node-unblocker#261]
I ask . For example, the blocked URL is https://jav.red. and I have my own Adstera popunder ad. I want my Adstera popunder ads to appear on that website with this node unblocker. is that possible

example  if i open 
https://myunblocker.com/proxy/https://jav.red

then in website run my code popunder ads 
thx

**Comment by nfriedly** [comment]
It's probably possible. You could do something like the [replace snippet](https://github.com/nfriedly/node-unblocker/tree/master/examples/replace_snippet) example and have it search for some existing tag, like `<body>` and replace it with something like `<body><advertisement/>`

**Comment by proudparrot2** [comment]
How to get people NOT to use your proxy instance:

**Comment by nfriedly** [comment]
Yeah, I'm just going to close this one.
