### ISSUE TITLE
Major sites like Facebook, Twitter and Google not working

### ISSUE THREAD

**Issue by bountyx** [nfriedly/node-unblocker#35]
None of the google logins work, they just throw an error after attempting to login.
Twitter's password field cannot be typed into, it just remains blank when attempting to type a password.
Facebook keeps throwing redirect notifications

**Comment by nfriedly** [comment]
Hey, I'm cleaning up old issues. I no longer have a live proxy, but the codebase has seen a lot of improvement recently. Please try running your own copy and let me know how it goes.

**Comment by SliiCkYT101** [comment]
ye
