### ISSUE TITLE
Implement some sort of URL "garbling"

### ISSUE THREAD

**Issue by CoolOppo** [nfriedly/node-unblocker#36]
I will admit, I definitely agree that the fact that URLs do not need to be altered aside from changing the site root is wonderful! While I would absolutely love to be able to use node-unblocker like this, it is unfortunately detected by the web filtering in use at my workplace. When I use the "encode URLs" feature offered by Glype, I have no issues, but it will be blocked just the same if I don't use that feature.

If there is any way to make it so that the URLs are able to be more random, or a way to exclude the indicators that I am accessing another domain name (like the `http://` and `.com` parts in the URL), that would be absolutely lovely!

**Comment by nfriedly** [comment]
Hey, I'm going to close this for now. With the current design and goals, I don't think it's very feasible.
