### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by intlabs** [nfriedly/node-unblocker#38]
Hi,

I'm trying to put node-unblocker behind a reverse proxy for intranet access:

I need to have under a subdirectory, and have modified the code to point to /canny/browser as it's root and it is working perfectly on it's own. But when I put nginx infront of node-unblocker I get stuck in a redirect loop:

curling node-unblocker directly results in the expected output:
```
curl -i http://172.16.6.168:800/canny/browser/proxy/http://example.com/
**expected output**
```

while the proxy returns:
```
curl -i http://172.16.6.168/canny/browser/proxy/http://example.com
HTTP/1.1 307 Temporary Redirect
Date: Wed, 25 Mar 2015 13:28:05 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: unblocker.sid=s%3AOWn3F7Kx4eGCwtoTxgeui6ui.w0vbLLD3wwWYHCXUQly85wTf0PhwEj9S89ccLrhrQCo; Path=/
location: http://172.16.6.168/canny/browser/proxy/http://localhost/canny/browser/proxy
```

The relevant section of my nginx config is:

```
location /canny/browser/ {
		proxy_pass        http://X.X.X.X:XX/canny/browser/;
		proxy_http_version 1.1;
		proxy_pass_header Server;
		proxy_redirect off;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
        }
```

Im sure i must be missing something pretty simple? If you had any pointers it would be greatly appreciated.

Cheers

Pete

**Comment by intlabs** [comment]
Fixed it:
```
merge_slashes off;
```
and its great :)

nice little proxy too!

**Comment by nfriedly** [comment]
Hey, sorry, I've been sick an not very responsive for the the past couple of days, but I'm glad to hear that you figured it out.
