### ISSUE TITLE
V1.0 trouble with npm start

### ISSUE THREAD

**Issue by unixabg** [nfriedly/node-unblocker#42]
Greetings,

Trying to install and run from git or zip download on Linux Mint 17.1 32bit , npm install appears to run ok:

lmint@lmint-VirtualBox ~/scratch/node-unblocker-master/examples/nodeunblocker.com $ sudo npm install
npm WARN engine unblocker@1.0.3: wanted: {"node":"0.12.x","npm":"2.7.x"} (current: {"node":"0.12.5","npm":"2.11.2"})
express@4.13.0 node_modules/express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── array-flatten@1.1.0
├── cookie@0.1.3
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── fresh@0.3.0
├── range-parser@1.0.2
├── path-to-regexp@0.1.6
├── content-type@1.0.1
├── etag@1.7.0
├── vary@1.0.0
├── parseurl@1.3.0
├── content-disposition@0.5.0
├── serve-static@1.10.0
├── depd@1.0.1
├── qs@2.4.2
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── type-is@1.6.4 (media-typer@0.3.0, mime-types@2.1.2)
└── accepts@1.2.10 (negotiator@0.5.3, mime-types@2.1.2)

gatling@1.1.1 node_modules/gatling
└── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)

unblocker@1.0.3 node_modules/unblocker
├── cookie@0.1.3
├── set-cookie-parser@1.0.1
├── content-type@1.0.1
├── through@2.3.8
├── mime@1.3.4
├── tld@0.0.2
├── async@1.3.0
├── debug@2.2.0 (ms@0.7.1)
├── iconv-lite@0.4.11
└── lodash@3.10.0

newrelic@1.20.2 node_modules/newrelic

However npm start does not fair so well:
lmint@lmint-VirtualBox ~/scratch/node-unblocker-master/examples/nodeunblocker.com $ sudo npm start

> nodeunblocker.com@1.0.0 start /home/lmint/scratch/node-unblocker-master/examples/nodeunblocker.com
> ./node_modules/gatling/gatling.js ./app.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'through'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/lmint/scratch/node-unblocker-master/examples/nodeunblocker.com/app.js:16:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! nodeunblocker.com@1.0.0 start: `./node_modules/gatling/gatling.js ./app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodeunblocker.com@1.0.0 start script './node_modules/gatling/gatling.js ./app.js'.
npm ERR! This is most likely a problem with the nodeunblocker.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/gatling/gatling.js ./app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodeunblocker.com
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lmint/scratch/node-unblocker-master/examples/nodeunblocker.com/npm-debug.log

Here is teh output of the log file:

lmint@lmint-VirtualBox ~/scratch/node-unblocker-master/examples/nodeunblocker.com $ cat /home/lmint/scratch/node-unblocker-master/examples/nodeunblocker.com/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart nodeunblocker.com@1.0.0
6 info start nodeunblocker.com@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info nodeunblocker.com@1.0.0 Failed to exec start script
9 verbose stack Error: nodeunblocker.com@1.0.0 start: `./node_modules/gatling/gatling.js ./app.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid nodeunblocker.com@1.0.0
11 verbose cwd /home/lmint/scratch/node-unblocker-master/examples/nodeunblocker.com
12 error Linux 3.13.0-37-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v0.12.5
15 error npm  v2.11.2
16 error code ELIFECYCLE
17 error nodeunblocker.com@1.0.0 start: `./node_modules/gatling/gatling.js ./app.js`
17 error Exit status 1
18 error Failed at the nodeunblocker.com@1.0.0 start script './node_modules/gatling/gatling.js ./app.js'.
18 error This is most likely a problem with the nodeunblocker.com package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ./node_modules/gatling/gatling.js ./app.js
18 error You can get their info via:
18 error     npm owner ls nodeunblocker.com
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Any ideas?
Thanks.

**Comment by nfriedly** [comment]
Oh, shoot, I moved the google analytics stuff out of the main codebase to the nodeunblocker.com example, but I didn't copy over it's dependencies (the through module).

This should make it work: 

    npm install --save through

But I'll try and get out an updated build soon.
