### ISSUE TITLE
Redirect to wrong address using google

### ISSUE THREAD

**Issue by VitaliyKovalchuk** [nfriedly/node-unblocker#44]
Greetings,

I am testing latest git.Sometime using a search engine google.com your module redirect me to wrong url, (http://localhost/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=0CDwQFjACahUKEwjsv-r014LHAhUBhSwKHbq7AYo&url=%2Fproxy%2Fhttp%3A%2F%2Fwww.apple.com%2Fru%2Fstevejobs%2F&ei=1wG6Vaz4HoGKsgG694bQCA&usg=AFQjCNELu0sMKoBA1ZZwj5D57TXfU17AyA&bvm=bv.99028883,d.bGg instead of allaboutstevejobs.com/) to reproduce the problem you need to go to the google, search Steave Jobs and click on link "all about Steve Jobs.com"

**Comment by nfriedly** [comment]
That's odd...

**Comment by nfriedly** [comment]
So, it looks like google is using javascript to rewrite the links as you click on them. But, they aren't doing it correctly, so it looses the port number. This is, unfortunately, almost impossible to fix in a reliable fashion :(

The upshot is that if you run `sudo PORT=80 npm start` to host the proxy, (or, if you're on windows, you might be able to skip the `sudo` part) then you can access it at http://localhost/ without any port number, and things start working. Of course, if you navigate to allaboutstevejobs.com through the proxy, their broken css makes the site look wrong. (That's something I might be able to fix in the proxy, but I don't know if it's worth the trouble...)
