### ISSUE TITLE
Block access to local IPs

### ISSUE THREAD

**Issue by Porco-Rosso** [nfriedly/node-unblocker#56]
Sorry to be back so soon again.

I've just noticed that it is possible to reach local IP addresses through the proxy. (like 192.168.1.154) 

Is there a setting or some lines I can add to stop the proxy from reaching local IP addresses? I know I could create a whole vlan, but that would be overkill and interfere with the other nodejs services I have running on the same VM.

**Comment by nfriedly** [comment]
There's nothing built-in to do that, but it would be pretty easy to add as a custom middleware. Look at the `validateRequest` example in the readme: https://github.com/nfriedly/node-unblocker#requestmiddleware

You could use `ip.isPrivate(URL.parse('http://127.0.0.1/').hostname)` to do the hard part - https://www.npmjs.com/package/ip - it will return false for anything that isn't an IP, so you might want an extra check for localhost (and any other hostname's your concerned about).

( https://www.npmjs.com/package/hostname-is-private or https://www.npmjs.com/package/private-ips would guard against that, but neither is synchronous so they won't easily work as middleware for unblocker. You could have express run then before unblocker, but that's more work on your end.)
