### ISSUE TITLE
TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by mattvick** [nfriedly/node-unblocker#66]
The proxy is crashing on some sites. An example of a URL that causes the proxy to crash is: http://www.optimcore.com/

Here is the full error message:

    Air:simple matthew$ npm start

    > simple-unblocker-server@0.0.0 start /Users/matthew/Sites/node-unblocker-master/examples/simple
    > node server.js

    /Users/matthew/Sites/node-unblocker-master/examples/simple/node_modules/tld/lib/tld.js:80
        var parts = domain.split('.'),
                          ^

    TypeError: Cannot read property 'split' of null
        at registeredDomain (/Users/matthew/Sites/node-unblocker-master/examples/simple/node_modules/tld/lib/tld.js:80:23)
        at Object.exports.registered (/Users/matthew/Sites/node-unblocker-master/examples/simple/node_modules/tld/lib/tld.js:120:12)
        at rewriteCookiesAndLinks (/Users/matthew/Sites/node-unblocker-master/examples/simple/node_modules/unblocker/lib/cookies.js:97:27)
        at /Users/matthew/Sites/node-unblocker-master/examples/simple/node_modules/unblocker/lib/proxy.js:66:13
        at arraySome (/Users/matthew/Sites/node-unblocker-master/examples/simple/node_modules/lodash/index.js:1493:13)
        at Function.some (/Users/matthew/Sites/node-unblocker-master/examples/simple/node_modules/lodash/index.js:7051:14)
        at proxyResponse (/Users/matthew/Sites/node-unblocker-master/examples/simple/node_modules/unblocker/lib/proxy.js:65:43)
        at ClientRequest.<anonymous> (/Users/matthew/Sites/node-unblocker-master/examples/simple/node_modules/unblocker/lib/proxy.js:42:17)
        at ClientRequest.g (events.js:260:16)
        at emitOne (events.js:77:13)

    npm ERR! Darwin 15.2.0
    npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "start"
    npm ERR! node v4.2.3
    npm ERR! npm  v3.5.2
    npm ERR! code ELIFECYCLE
    npm ERR! simple-unblocker-server@0.0.0 start: `node server.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the simple-unblocker-server@0.0.0 start script 'node server.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the simple-unblocker-server package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node server.js
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs simple-unblocker-server
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls simple-unblocker-server
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/matthew/Sites/node-unblocker-master/examples/simple/npm-debug.log

and here is the contents of the log file:

	0 info it worked if it ends with ok
	1 verbose cli [ '/opt/local/bin/node', '/opt/local/bin/npm', 'start' ]
	2 info using npm@3.5.2
	3 info using node@v4.2.3
	4 verbose run-script [ 'prestart', 'start', 'poststart' ]
	5 info lifecycle simple-unblocker-server@0.0.0~prestart: simple-unblocker-server@0.0.0
	6 silly lifecycle simple-unblocker-server@0.0.0~prestart: no script for prestart, continuing
	7 info lifecycle simple-unblocker-server@0.0.0~start: simple-unblocker-server@0.0.0
	8 verbose lifecycle simple-unblocker-server@0.0.0~start: unsafe-perm in lifecycle true
	9 verbose lifecycle simple-unblocker-server@0.0.0~start: PATH: /opt/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/matthew/Sites/node-unblocker-master/examples/simple/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
	10 verbose lifecycle simple-unblocker-server@0.0.0~start: CWD: /Users/matthew/Sites/node-unblocker-master/examples/simple
	11 silly lifecycle simple-unblocker-server@0.0.0~start: Args: [ '-c', 'node server.js' ]
	12 silly lifecycle simple-unblocker-server@0.0.0~start: Returned: code: 1  signal: null
	13 info lifecycle simple-unblocker-server@0.0.0~start: Failed to exec start script
	14 verbose stack Error: simple-unblocker-server@0.0.0 start: `node server.js`
	14 verbose stack Exit status 1
	14 verbose stack     at EventEmitter.<anonymous> (/opt/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
	14 verbose stack     at emitTwo (events.js:87:13)
	14 verbose stack     at EventEmitter.emit (events.js:172:7)
	14 verbose stack     at ChildProcess.<anonymous> (/opt/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
	14 verbose stack     at emitTwo (events.js:87:13)
	14 verbose stack     at ChildProcess.emit (events.js:172:7)
	14 verbose stack     at maybeClose (internal/child_process.js:818:16)
	14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
	15 verbose pkgid simple-unblocker-server@0.0.0
	16 verbose cwd /Users/matthew/Sites/node-unblocker-master/examples/simple
	17 error Darwin 15.2.0
	18 error argv "/opt/local/bin/node" "/opt/local/bin/npm" "start"
	19 error node v4.2.3
	20 error npm  v3.5.2
	21 error code ELIFECYCLE
	22 error simple-unblocker-server@0.0.0 start: `node server.js`
	22 error Exit status 1
	23 error Failed at the simple-unblocker-server@0.0.0 start script 'node server.js'.
	23 error Make sure you have the latest version of node.js and npm installed.
	23 error If you do, this is most likely a problem with the simple-unblocker-server package,
	23 error not with npm itself.
	23 error Tell the author that this fails on your system:
	23 error     node server.js
	23 error You can get information on how to open an issue for this project with:
	23 error     npm bugs simple-unblocker-server
	23 error Or if that isn't available, you can get their info via:
	23 error     npm owner ls simple-unblocker-server
	23 error There is likely additional logging output above.
	24 verbose exit [ 1, true ]

**Comment by mattvick** [comment]
@nfriedly I've just noticed the crash is only happening which the proxied page is loaded in an iframe. I have no idea why this might be so I will investigate this further

**Comment by nfriedly** [comment]
Hum... that's odd. It definately shouldn't be crashing, although when I run the proxy locally and visit http://www.optimcore.com/ it works for me. Could you run it again with `DEBUG=* npm start` and give me the full output? It should include a ton of debugging info.

**Comment by mattvick** [comment]
Here you go: http://pastebin.com/JLDzX7kX

**Comment by mattvick** [comment]
FYI I'm building a visual website editor and using the node proxy to circumvent same-origin policy. A PHP app creates an iframe into which a webpage is loaded using the node proxy. The PHP app is running on port 80, the node proxy is running on port 8080 and I'm using Apache to proxy requests to Node.js as follows:

    <VirtualHost *:80>
        ServerName ocl
        ServerAlias ocl.com
        DirectoryIndex app.php
        DocumentRoot /Users/matthew/Sites/ocl/web
        <Directory /Users/matthew/Sites/ocl/web>
            AllowOverride All
            Order allow,deny
            Allow from All
        </Directory>
        <Location "/proxy">
            ProxyPass http://localhost:8080/proxy
            ProxyPassReverse http://localhost:8080/proxy
        </Location>
    </VirtualHost>

**Comment by nfriedly** [comment]
Hey, sorry it took me forever to get back to you, but I think I finally figured it out. The key is on line 555 of your debug output:

      unblocker:proxy proxying GET http:/www.optimcore.com/js/jquery.min.map +3ms

There should be two slashes after http:, but there's only one. Something is probably trying to be clever and "fix" that for you. I'll see if I can make the proxy a bit more resilient against that kind of shennanagain. At worst, it should just drop the request with a 404, but ideally it should silently fix the URL.

**Comment by nfriedly** [comment]
I just released `v1.0.10` with a fix to detect "http:/" urls and redirect them to "http://" ones. I know it's been quite a while, but if you get the chance, please try it out and let me know if it works for you.

**Comment by mattvick** [comment]
This is great, many thanks!

I can't find what was generating the single slash url, perhaps it was a typo that has since been fixed. 

Recently I had been investigating another issue: When loading the webpage http://www.survio.com/l-cs-dotaznik-form/ via the proxy. Several resources were randomly returning 5xx errors. The logs were showing a similar `domain.split('.')` issue:

    /var/app/current/node_modules/tld/lib/tld.js:80
        var parts = domain.split('.'),
                          ^

Here are more of the logs: http://pastebin.com/xWwkdWmE

There don't appear to be any malformed (single slash) urls on the survio.com page, but the good news is your new release has also fixed this issue :)

Do you think the cause of this could be something other than the single slash?

Many thanks,
Matthew
