### ISSUE TITLE
Protocol strings defined in Yandex Metrica script tag incorrectly proxified

### ISSUE THREAD

**Issue by mattvick** [nfriedly/node-unblocker#74]
Below is the [Yandex Metrica](https://metrica.yandex.com) script tag from the webpage http://www.survio.com/l-cs-dotaznik-form/ 

    <script type="text/javascript">
    (function(d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter24267952 = new Ya.Metrika({
                    id: 24267952,
                    clickmap: true,
                    trackLinks: true,
                    accurateTrackBounce: true
                });
            } catch (e) {}
        });
        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function() {
                n.parentNode.insertBefore(s, n);
            };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";
        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else {
            f();
        }
    })(document, window, "yandex_metrika_callbacks");
    </script>

When this page is loaded via the unblocker proxy this script is rewritten as follows:

    <script type="text/javascript">
    (function(d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter24267952 = new Ya.Metrika({
                    id: 24267952,
                    clickmap: true,
                    trackLinks: true,
                    accurateTrackBounce: true
                });
            } catch (e) {}
        });
        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function() {
                n.parentNode.insertBefore(s, n);
            };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "/proxy/https:" ? "/proxy/https:" : "/proxy/http:") + "/proxy/http://mc.yandex.ru/metrika/watch.js";
        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else {
            f();
        }
    })(document, window, "yandex_metrika_callbacks");
    </script>

The script then creates the following url: `/proxy/http://proxy/http://mc.yandex.ru/metrika/watch.js`, which is not correct and causes a 500 error.

**Comment by mattvick** [comment]
Here's the full debug log: http://pastebin.com/rsjYr1GW

**Comment by nfriedly** [comment]
aah, that's a trickey case. Let me see if I can get a good fix in place. Nice work tracking it down.

**Comment by nfriedly** [comment]
I think this should be fixed in `v1.0.11`, again please try it out and let me know.

**Comment by mattvick** [comment]
Thanks for investigating and sorry for the delay in responding. I've deployed and tested the new version and this appears to still be broken. The source of http://www.optimcore.com/proxy/http://www.survio.com/l-cs-dotaznik-form/ contains a `script` tag with a badly proxied `src` attribute:

`<script type="text/javascript" async="" src="/proxy/http:/proxy/http://mc.yandex.ru/metrika/watch.js"></script>`
