### ISSUE TITLE
Logins not working

### ISSUE THREAD

**Issue by baaaaaaaaaaaaaam** [nfriedly/node-unblocker#8]
First off, this is a great project -- I'm really impressed at how fast it is compared to similar projects (Glype, CGIProxy)

I was just wondering if you had a fix / had thought about how to process logins.  I've tried numerous sites, and none work (Google, LinkedIn, etc.).

Thanks

**Comment by nfriedly** [comment]
Hey, I'm cleaning up old issues. I no longer have a live proxy, but the codebase has seen a lot of improvement recently. Please try running your own copy and let me know how it goes.
