### ISSUE TITLE
Cant start server on windows

### ISSUE THREAD

**Issue by lephuongbac** [nfriedly/node-unblocker#80]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart nodeunblocker.com@1.0.0
6 info start nodeunblocker.com@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info nodeunblocker.com@1.0.0 Failed to exec start script
9 verbose stack Error: nodeunblocker.com@1.0.0 start: `./node_modules/gatling/gatling.js ./app.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid nodeunblocker.com@1.0.0
11 verbose cwd C:\Users\Administrator\Desktop\node-unblocker\examples\nodeunblocker.com
12 error Windows_NT 6.2.9200
13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.5
15 error npm  v2.15.5
16 error code ELIFECYCLE
17 error nodeunblocker.com@1.0.0 start: `./node_modules/gatling/gatling.js ./app.js`
17 error Exit status 1
18 error Failed at the nodeunblocker.com@1.0.0 start script './node_modules/gatling/gatling.js ./app.js'.
18 error This is most likely a problem with the nodeunblocker.com package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ./node_modules/gatling/gatling.js ./app.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs nodeunblocker.com
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls nodeunblocker.com
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by nfriedly** [comment]
Hi @lephuongbac can you also post the console output? (I don't know why, but npm-debug.log files don't include it.)

**Comment by lephuongbac** [comment]
Hi @nfriedly 
please see console output bellow
```
C:\node-unblocker\examples\nodeunblocker.com>npm install
through@2.3.8 node_modules\through

gatling@1.2.0 node_modules\gatling
└── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)

express@4.14.0 node_modules\express
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── cookie-signature@1.0.6
├── utils-merge@1.0.0
├── methods@1.1.2
├── encodeurl@1.0.1
├── content-type@1.0.2
├── merge-descriptors@1.0.1
├── cookie@0.3.1
├── content-disposition@0.5.1
├── etag@1.7.0
├── fresh@0.3.0
├── parseurl@1.3.1
├── range-parser@1.2.0
├── vary@1.1.0
├── serve-static@1.11.1
├── path-to-regexp@0.1.7
├── depd@1.1.0
├── qs@6.2.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.0)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
├── send@0.14.1 (destroy@1.0.4, ms@0.7.1, statuses@1.3.0, mime@1.3.4, http-error
s@1.5.0)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)
└── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.11)

newrelic@1.28.1 node_modules\newrelic

unblocker@1.1.1 node_modules\unblocker
├── set-cookie-parser@1.0.2
├── content-type@1.0.2
├── cookie@0.2.4
├── tld@0.0.2
├── async@1.5.2
├── mime@1.3.4
├── debug@2.2.0 (ms@0.7.1)
├── iconv-lite@0.4.13
└── lodash@4.13.1

C:\node-unblocker\examples\nodeunblocker.com>npm start

> nodeunblocker.com@1.0.0 start C:\node-unblocker\examples\nodeunblocker.com
> ./node_modules/gatling/gatling.js ./app.js

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! nodeunblocker.com@1.0.0 start: `./node_modules/gatling/gatling.js ./app
.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodeunblocker.com@1.0.0 start script './node_modules/gatl
ing/gatling.js ./app.js'.
npm ERR! This is most likely a problem with the nodeunblocker.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/gatling/gatling.js ./app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodeunblocker.com
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls nodeunblocker.com
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\node-unblocker\examples\nodeunblocker.com\npm-debug.log

C:\node-unblocker\examples\nodeunblocker.com>
```

**Comment by nfriedly** [comment]
Aah, try changing [this line](https://github.com/nfriedly/node-unblocker/blob/master/examples/nodeunblocker.com/package.json#L20) to:

```js
 "start": "node ./node_modules/gatling/gatling.js ./app.js"
```

And let me know if `npm start` works after that

**Comment by lephuongbac** [comment]
thank you, it works.

**Comment by nfriedly** [comment]
Cool, sorry for the trouble
