### ISSUE TITLE
<meta http-equiv="refresh"... not parsed

### ISSUE THREAD

**Issue by emilhem** [nfriedly/node-unblocker#85]
I tested this site that used IPv6. If you don't have IPv6 it returns a page with the following (only):
```HTML
<META HTTP-EQUIV="Refresh" CONTENT="0;URL=http://support.bredbandskollen.se/support/solutions/articles/1000212163-vad-r-ipv6-och-hur-fungerar-bredbandskollen-ver-ipv6">
```
Headers:
```
HTTP/1.1 200 OK
Date: Mon, 11 Jul 2016 14:24:35 GMT
Server: Apache/2.2.22 (Debian)
X-Powered-By: PHP/5.4.45-0+deb7u2
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 157
Content-Type: text/html
```
This is the page that does this: http://ipv6.bredbandskollen.se/

The issue is that the url parsing doesn't catch this one even though the content-type is text/html...

**Comment by nfriedly** [comment]
I think [this regex here](https://github.com/nfriedly/node-unblocker/blob/master/lib/url-prefixer.js#L22) just needs to be updated to also match `URL=`. Add a test or two and try that.

**Comment by nfriedly** [comment]
Actually, that might not be right [this one](https://github.com/nfriedly/node-unblocker/blob/master/lib/url-prefixer.js#L20) should be matching that line, so I'm not sure why it isn't...

**Comment by emilhem** [comment]
Yep, I tested that. It matches it but when I add a `console.log` in `url-prefixer.js` function `rewriteUrls` this is the response from the chunks before and after parsing:
```HTML
<META HTTP-EQUIV="Refresh"
```
It doesn't parse the part after that it seems. Strange!

Alas, I think I found the missing part! In `url-prefixer.js` the `flush` function has a chunk remainder.

**Comment by emilhem** [comment]
When I change [this](https://github.com/nfriedly/node-unblocker/blob/master/lib/url-prefixer.js#L87) to `this.push(rewriteUrls(chunk_remainder, uri, config.prefix));`. It solves the issue. The tests pass as well.

**Comment by emilhem** [comment]
My pull request #86 solves this issue.
